name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    name: .NET Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x    
    
    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  deploy:
    name: Docker Build & Heroku Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Heroku Authenticate
      run: yes '${{ secrets.HEROKU_EMAIL }}\n${{ secrets.HEROKU_API_KEY }}\n\n\n\n' | heroku login -i
     
    - name: Docker Authenticate
      run: heroku container:login
     
    - name: Docker Build
      run: docker build . --file Dockerfile --tag synserver:main
      
    - name: Docker Tag
      run: docker tag synserver:main registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Docker Push
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
    
    - name: Heroku Release
      run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }} --recursive
