name: Heroku Docker Container Deploy

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x    
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Docker Authenticate
      run: docker login --username=${{ secrets.HEROKU_EMAIL }} --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
        
    - name: Docker Build
      run: docker build . --file Dockerfile
      
    - name: Docker Tag
      run: docker tag synserver:$(date +%s) registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Docker Push
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
