name: Trigger auto deployment for syn

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/syn-AutoDeployTrigger-3643b697-b366-4e49-8d14-8d8935a3eb87.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: index.docker.io/v1
          username: ${{ secrets.SYN_REGISTRY_USERNAME }}
          password: ${{ secrets.SYN_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/v1/syn:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SYN_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n syn -g DefaultResourceGroup-CUS --server index.docker.io/v1 --username  ${{ secrets.SYN_REGISTRY_USERNAME }} --password ${{ secrets.SYN_REGISTRY_PASSWORD }}
            az containerapp update -n syn -g DefaultResourceGroup-CUS --image index.docker.io/v1/syn:${{ github.sha }}
