name: Trigger auto deployment for syn

on:
  push:
    branches: 
      [ main ]
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: index.docker.io
          username: ${{ secrets.SYN_REGISTRY_USERNAME }}
          password: ${{ secrets.SYN_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/${{ secrets.SYN_REGISTRY_USERNAME }}/synserver:${{ github.sha }}
          file: ./Dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SYN_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n syn -g DefaultResourceGroup-CUS --server index.docker.io --username  ${{ secrets.SYN_REGISTRY_USERNAME }} --password ${{ secrets.SYN_REGISTRY_PASSWORD }}
            az containerapp update -n syn -g DefaultResourceGroup-CUS --image index.docker.io/${{ secrets.SYN_REGISTRY_USERNAME }}/synserver:${{ github.sha }}
